### PR TITLE
Add lazy_load option

### LINKED ISSUE #26: Idea to improve performance
For  lithweight page and better performance, do not load the iframe but only the thumbnail.
https://www.labnol.org/internet/light-youtube-embeds/27941/

### PR DESCRIPTION
**Pull request by TheDancingCode**
With `lazy_load` enabled, the YouTube preview thumbnail and play button are displayed. When clicked, the iframe gets loaded and the video automatically starts playing.

Requires both `lazy_load` and `built_in_js` to be enabled.

Closes #26.

### CODE REVIEW

**Comment by TheDancingCode** [comment]
Any thoughts on this?

**Comment by leycec** [comment]
This is also a hard prerequisite for GDPR compatibility at #27 – notably:

> So let it load only the thumbnail from ytimg.com or an own thumbnail

Well, that's nice. What say ye, Grand Grav Master @mahagr?

**Comment by angusmcb** [comment]
I have started using this on my site - massively reduced the page load time for slow connections :-)

**Comment by 01Kuzma** [comment]
After enabling lazy load function the `pageSpeed Insights` still warns about:
**Remove unused JavaScript**:
en_US/base.js(www.youtube.com)
www-embed-player.vflset/www-embed-player.js(www.youtube.com)

and

**Remove unused CSS**
9f996d3e/www-player.css(www.youtube.com)

Is it normal behavior or `lazy-load` is not functioning properly?
Placed as shortcode in `Custom HTML` particle in Gantry 5 framework, `Process shortcodes` is turned on

**Pull request merged**
